<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">导言</a></dt>
    <dd>为什么要选另一款会计软件?</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualCreatingNewSystem.html">创建一个新系统</a></dt>
    <dd>运行演示数据库</dd>
    <dd>设置系统</dd>
    <dd>设置库存商品</dd>
    <dd>输入库存余额</dd>
    <dd>库存总帐整合到总帐</dd>
    <dd>设置顾客</dd>
    <dd>输入顾客余额</dd>
    <dd>应收账款核对</dd>
    <dd>结尾</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualSystemConventions.html">系统惯例</a></dt>
    <dd>菜单导航</dd>
    <dd>报告</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualInventory.html">库存("存货")</a></dt>
    <dd>概述</dd>
    <dd>库存系统特性</dd>
    <dd>库存种类</dd>
    <dd>增加库存商品</dd>
    <dd>商品代码</dd>
    <dd>部品描述</dd>
    <dd>种类</dd>
    <dd>计量单位</dd>
    <dd>经济订购数量</dd>
    <dd>包装体积</dd>
    <dd>包装重量</dd>
    <dd>计量单位</dd>
    <dd>当前或淘汰</dd>
    <dd>制造或者购买</dd>
    <dd>设置组装商品</dd>
    <dd>受控</dd>
    <dd>序列化</dd>
    <dd>条码</dd>
    <dd>折扣种类</dd>
    <dd>小数位数</dd>
    <dd>库存成本</dd>
    <dd>物料成本</dd>
    <dd>劳力成本</dd>
    <dd>制造费用</dd>
    <dd>标准成本考量</dd>
    <dd>实际成本</dd>
    <dd>变更劳力成本，物料成本或者制造费用</dd>
    <dd>选择库库存商品</dd>
    <dd>修改库存商品</dd>
    <dd>修改库存种类</dd>
    <dd>修改为制造或者购买标识</dd>
    <dd>库存种类</dd>
    <dd>库存种类代码</dd>
    <dd>库存种类描述</dd>
    <dd>资产负债表库存总帐账户</dd>
    <dd>库存调整总帐过账账户</dd>
    <dd>采购价格差异账户</dd>
    <dd>物料用量差异账户</dd>
    <dd>资源类型</dd>
    <dd>库存地点维护</dd>
    <dd>库存调整</dd>
    <dd>库存地点转移</dd>
    <dd>库存报告和查询</dd>
    <dd>库存状态查询</dd>
    <dd>库存变化查询</dd>
    <dd>库存用量查询</dd>
    <dd>库存价值报告</dd>
    <dd>库存计划报告</dd>
    <dd>库存盘点</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">应收账款</a></dt>
    <dd>概述</dd>
    <dd>特性</dd>
    <dd>输入新顾客</dd>
    <dd>顾客代码</dd>
    <dd>顾客名称</dd>
    <dd>地址行1,2,3和4</dd>
    <dd>货币</dd>
    <dd>发票折扣</dd>
    <dd>即付折扣</dd>
    <dd>顾客交易起始日</dd>
    <dd>付款条件</dd>
    <dd>信用状况或评级</dd>
    <dd>信用额度</dd>
    <dd>发票地址</dd>
    <dd>输入顾客分公司</dd>
    <dd>分公司名称</dd>
    <dd>分公司代码</dd>
    <dd>分公司联络人/电话/传真/地址</dd>
    <dd>销售人员</dd>
    <dd>提货仓库</dd>
    <dd>Forward Date From A Day In The Month</dd>
    <dd>付运天数</dd>
    <dd>电话/传真/电邮</dd>
    <dd>税收当局</dd>
    <dd>停止交易</dd>
    <dd>默认运输公司</dd>
    <dd>邮件地址1,2,3和4</dd>
    <dd>修改顾客细节</dd>
    <dd>承运人</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">应付账款</a></dt>
    <dd>概述</dd>
    <dd>特性</dd>
    <dd>输入新供应商</dd>
    <dd>供应商代码</dd>
    <dd>供应商名称</dd>
    <dd>地址行1，2，3和4</dd>
    <dd>供应商交易起始日</dd>
    <dd>付款条件</dd>
    <dd>Bank Particulars/Reference</dd>
    <dd>银行账户号码</dd>
    <dd>货币</dd>
    <dd>汇款通知</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">销售人员</a></dt>
    <dd>销售人员记录</dd>
    <dd>销售人员代码</dd>
    <dd>销售人员名称，电话，和传真</dd>
    <dd>销售人员佣金率和折扣点</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">货币</a></dt>
    <dd>货币缩写</dd>
    <dd>货币名称</dd>
    <dd>货币国家</dd>
    <dd>货币百分单位名称</dd>
    <dd>汇率</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">销售类型/价格表</a></dt>
    <dd>销售类型/价格表</dd>
    <dd>销售类型代码</dd>
    <dd>销售类型描述</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">付款条件</a></dt>
    <dd>付款条件</dd>
    <dd>付款条件代码</dd>
    <dd>付款条件描述</dd>
    <dd>到期天数/下个月某天到期</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">信用状况</a></dt>
    <dd>信用状况评级</dd>
    <dd>信用状况代码</dd>
    <dd>状况描述</dd>
    <dd>禁止开发票</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">税收</a></dt>
    <dd>税收计算</dd>
    <dd>概述</dd>
    <dd>设置税收</dd>
    <dd>一个税务机关内的销售例子--2个税收水平:</dd>
    <dd>一个税务机关内销售的例子--3个税收水平:</dd>
    <dd>两个税务机关内销售的例子--3个税收水平:</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">价格和折扣</a></dt>
    <dd>价格和折扣</dd>
    <dd>定价概述</dd>
    <dd>维护价格</dd>
    <dd>折扣矩阵</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">应收账款交易</a></dt>
    <dd>为订单开发票</dd>
    <dd>选择要开发票的订单</dd>
    <dd>从选择的订单生成发票</dd>
    <dd>红字发票</dd>
    <dd>收款输入</dd>
    <dd>收款 - 顾客</dd>
    <dd>收款 - 日期</dd>
    <dd>收款 - 货币和汇率</dd>
    <dd>收款 - 付款方式</dd>
    <dd>收款 - 金额</dd>
    <dd>收款 - 折扣</dd>
    <dd>收款 - 分配至发票</dd>
    <dd>汇率差异</dd>
    <dd>收款处理</dd>
    <dd>存款列表</dd>
    <dd>分配红字款项给顾客</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">应收账款查询</a></dt>
    <dd>顾客查询</dd>
    <dd>顾客账户查询</dd>
    <dd>交易细节查询</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">应收账款报告</a></dt>
    <dd>顾客 - 报告</dd>
    <dd>过期顾客账户表</dd>
    <dd>顾客对账单</dd>
    <dd>顾客交易列表选项</dd>
    <dd>打印发票或红字发票</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">销售分析</a></dt>
    <dd>销售分析</dd>
    <dd>销售分析报告表头</dd>
    <dd>销售分析报告栏</dd>
    <dd>自动销售报告</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">销售订单</a></dt>
    <dd>销售订单</dd>
    <dd>销售订单功能</dd>
    <dd>输入销售订单</dd>
    <dd>销售订单 - 选择顾客和分公司</dd>
    <dd>选择订单行商品</dd>
    <dd>交付细节</dd>
    <dd>修改订单</dd>
    <dd>报价单</dd>
    <dd>周期订单</dd>
    <dd>柜台销售 - 直接输入销售</dd>
    <dd>根据产品组或者顾客组（矩阵）管理折扣</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">采购订单</a></dt>
    <dd>概述</dd>
    <dd>采购订单</dd>
    <dd>增加新采购订单</dd>
    <dd>采购订单授权</dd>
    <dd>采购订单收货</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">运输</a></dt>
    <dd>运输</dd>
    <dd>运输总帐过账</dd>
    <dd>创建运输</dd>
    <dd>运输成本</dd>
    <dd>关闭运输</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">合同成本</a></dt>
    <dd>合同成本概述</dd>
    <dd>创建新合同</dd>
    <dd>选择合同</dd>
    <dd>合同付费</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">制造</a></dt>
    <dd>制造概述</dd>
    <dd>总帐意义</dd>
    <dd>工单输入</dd>
    <dd>工单收货</dd>
    <dd>工单发料</dd>
    <dd>关闭工单</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">物料需求计划</a></dt>
    <dd>MRP 概述</dd>
    <dd>基础数据需求</dd>
    <dd>生产日历</dd>
    <dd>主（生产）计划</dd>
    <dd>运行MRP计算</dd>
    <dd>工作原理</dd>
    <dd>MRP 报告</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">总帐</a></dt>
    <dd>总帐概述</dd>
    <dd>科目组</dd>
    <dd>银行账户</dd>
    <dd>银行账户付款</dd>
    <dd>总帐整合设置</dd>
    <dd>销售分录</dd>
    <dd>库存分录</dd>
    <dd>EDI</dd>
    <dd>EDI设置</dd>
    <dd>发送EDI发票</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">固定资产</a></dt>
    <dd>固定资产概述</dd>
    <dd>创建固定资产</dd>
    <dd>选择固定资产</dd>
    <dd>运行折旧</dd>
    <dd>固定资产计划</dd>
</dl>

<dl>
    <dt><a href="ManualContents.php?ViewTopic=ManualIntroduction.html">小额现金管理系统</a></dt>
    <dd>概述</dd>
    <dd>设置基本参数</dd>
</dl>
